# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: '051bc29cf263cca17edc2efcb721e3a623d0f725216c5662eb7d5da30105754036500c5bdae5f46ad186d64da794ec7b99324a1c073793c4fa906dd1d81251d6'

test:
  secret_key_base: '051bc29cf263cca17edc2efcb721e3a623d0f725216c5662eb7d5da30105754036500c5bdae5f46ad186d64da794ec7b99324a1c073793c4fa906dd1d81251d6'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# # spree_social
#   FACEBOOK_APP_ID: 195469684245895
#   FACEBOOK_APP_SECRET: 3482a41301b0b11dbf6c7c5013305816

development:
  S3_BUCKET_NAME: b4dcity-development 
  AWS_ACCESS_KEY_ID: AKIAISPR3Z4PQNE44TJQ 
  AWS_SECRET_ACCESS_KEY: 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 
  AWS_REGION: us-west-2
  FACEBOOK_APP_ID: 195469684245895
  FACEBOOK_APP_SECRET: 3482a41301b0b11dbf6c7c5013305816
production:
  S3_BUCKET_NAME: b4dcity-production 
  AWS_ACCESS_KEY_ID: AKIAISPR3Z4PQNE44TJQ 
  AWS_SECRET_ACCESS_KEY: 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 
  AWS_REGION: us-west-2  
  FACEBOOK_APP_ID: 195469684245895
  FACEBOOK_APP_SECRET: 3482a41301b0b11dbf6c7c5013305816
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
